# Generated by Django 4.0.2 on 2022-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
